### ISSUE TITLE
'Player' AnimationEvent 'OnLand' on animation 'Run_N_Land' has no receiver! Are you missing a component?

### ISSUE THREAD

**Issue by ghost** [LarsGielen/The-Last-Human-in-Space#10]
Tijdens het rondlopen krijg ik:

" 'Player' AnimationEvent 'OnLand' on animation 'Run_N_Land' has no receiver! Are you missing a component? "

Het spel blijft verder werken, maar wou het toch even laten weten voor het geval dit nog niet opgevallen was.

**Comment by LarsGielen** [comment]
Dat zijn de animatie events die de juiste functie niet vinden, hier moet inderdaad nog iets voor gemaakt worden. Het staat ook al als todo in milanote
