### ISSUE TITLE
MouseInput_werkt_niet

### ISSUE THREAD

**Issue by ghost** [LarsGielen/The-Last-Human-in-Space#8]
Wanneer `Move With Mouse` = true en ik klik ergens loopt de speler er niet naar toe. 
Versie: Is gepullde larsbranch 18/08 om 10u.

[MouseInput_werkt_niet_Video.zip](https://github.com/LarsGielen/The-Last-Human-in-Space/files/12385356/MouseInput_werkt_niet.zip)

**Comment by LarsGielen** [comment]
Bij `RayCastLayerMask` moeten alle grond layers aangeduid worden, in dit geval dus 'Default'.

Ik zie ook dat de speler in jouw scene niet afstamt van de speler prefab, ik raad aan om de speler te verwijderen en de speler prefab toe te voegen aan de scene. Op deze manier zouden alle instellingen juist moeten staan en automatisch veranderen als er aanpassingen worden gemaakt in andere scenes. Vergeet niet de `PlayerCameraRoot` als `Follow` en `LookAt` target te zetten in de `PlayerFollowCamera`
